/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.IntelliJTheme;
import javax.swing.UIManager;
import model.CompositeEmployee;
import model.LeafEmployee;

/**
 *
 * @author NUWAA
 */
public class AllionSalaryCalculator extends javax.swing.JFrame {

    LeafEmployee brayan;
    LeafEmployee nevil;
    LeafEmployee rohan;
    LeafEmployee keeth;
    CompositeEmployee rayan;
    CompositeEmployee kathrina;
    CompositeEmployee donald;
    CompositeEmployee andrew;

    /**
     * Creates new form AllionSalaryCalculator
     */
    public AllionSalaryCalculator() {
        initComponents();

        brayan = new LeafEmployee("Brayan", "Software Developer", 100000.00);
        nevil = new LeafEmployee("Nevil", "Software Developer", 100000.00);
        rohan = new LeafEmployee("Rohan", "Software Developer", 100000.00);
        keeth = new LeafEmployee("Keeth", "Software Developer", 100000.00);

        rayan = new CompositeEmployee("Rayan", "Project Manager", 180000.0);
        kathrina = new CompositeEmployee("Kathrina", "Project Manager", 180000.0);
        donald = new CompositeEmployee("Donald", "Project Manager", 180000.0);

        andrew = new CompositeEmployee("Andrew", "Manager", 250000.0);

        rayan.addEmployee(brayan);
        kathrina.addEmployee(nevil);
        kathrina.addEmployee(rohan);
        donald.addEmployee(keeth);

        andrew.addEmployee(rayan);
        andrew.addEmployee(kathrina);
        andrew.addEmployee(donald);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        allEmployeesButton = new javax.swing.JButton();
        andrewButton = new javax.swing.JButton();
        rayanButton = new javax.swing.JButton();
        kathrinaButton = new javax.swing.JButton();
        donaldButton = new javax.swing.JButton();
        brayanButton = new javax.swing.JButton();
        nevilButton = new javax.swing.JButton();
        rohanButton = new javax.swing.JButton();
        keethButton = new javax.swing.JButton();
        rayanAndTeamButton = new javax.swing.JButton();
        kathrinaAndTeamButton = new javax.swing.JButton();
        donaldAndTeamButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Allion Software Solutions PVT LTD / Salary Calculator");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Allion Software Solutions PVT LTD / Salary Calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Calculate Salary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        allEmployeesButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        allEmployeesButton.setText("All Employees");
        allEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allEmployeesButtonActionPerformed(evt);
            }
        });

        andrewButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        andrewButton.setText("Andrew");
        andrewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andrewButtonActionPerformed(evt);
            }
        });

        rayanButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rayanButton.setText("Rayan");
        rayanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rayanButtonActionPerformed(evt);
            }
        });

        kathrinaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kathrinaButton.setText("Kathrina");
        kathrinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kathrinaButtonActionPerformed(evt);
            }
        });

        donaldButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        donaldButton.setText("Donald");
        donaldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donaldButtonActionPerformed(evt);
            }
        });

        brayanButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        brayanButton.setText("Brayan");
        brayanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brayanButtonActionPerformed(evt);
            }
        });

        nevilButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nevilButton.setText("Nevil");
        nevilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevilButtonActionPerformed(evt);
            }
        });

        rohanButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rohanButton.setText("Rohan");
        rohanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rohanButtonActionPerformed(evt);
            }
        });

        keethButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        keethButton.setText("Keeth");
        keethButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keethButtonActionPerformed(evt);
            }
        });

        rayanAndTeamButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rayanAndTeamButton.setText("Rayan And Team");
        rayanAndTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rayanAndTeamButtonActionPerformed(evt);
            }
        });

        kathrinaAndTeamButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kathrinaAndTeamButton.setText("Kathrina And Team");
        kathrinaAndTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kathrinaAndTeamButtonActionPerformed(evt);
            }
        });

        donaldAndTeamButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        donaldAndTeamButton.setText("Donald And Team");
        donaldAndTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donaldAndTeamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allEmployeesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(andrewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rayanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kathrinaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donaldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(brayanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rohanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nevilButton, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keethButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rayanAndTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kathrinaAndTeamButton, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donaldAndTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allEmployeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(andrewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rayanAndTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kathrinaAndTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donaldAndTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rayanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kathrinaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donaldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brayanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nevilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keethButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rohanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Salary : ");

        salaryLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        salaryLabel.setText("0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLabel)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void allEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allEmployeesButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(andrew.getSalary(true) + " LKR");
    }//GEN-LAST:event_allEmployeesButtonActionPerformed

    private void andrewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andrewButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(andrew.getSalary(false) + " LKR");
    }//GEN-LAST:event_andrewButtonActionPerformed

    private void rayanAndTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rayanAndTeamButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(rayan.getSalary(true) + " LKR");
    }//GEN-LAST:event_rayanAndTeamButtonActionPerformed

    private void kathrinaAndTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kathrinaAndTeamButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(kathrina.getSalary(true) + " LKR");
    }//GEN-LAST:event_kathrinaAndTeamButtonActionPerformed

    private void donaldAndTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donaldAndTeamButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(donald.getSalary(true) + " LKR");
    }//GEN-LAST:event_donaldAndTeamButtonActionPerformed

    private void rayanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rayanButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(rayan.getSalary(false) + " LKR");
    }//GEN-LAST:event_rayanButtonActionPerformed

    private void kathrinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kathrinaButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(kathrina.getSalary(false) + " LKR");
    }//GEN-LAST:event_kathrinaButtonActionPerformed

    private void donaldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donaldButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(donald.getSalary(false) + " LKR");
    }//GEN-LAST:event_donaldButtonActionPerformed

    private void brayanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brayanButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(brayan.getSalary(false) + " LKR");
    }//GEN-LAST:event_brayanButtonActionPerformed

    private void nevilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevilButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(nevil.getSalary(false) + " LKR");
    }//GEN-LAST:event_nevilButtonActionPerformed

    private void rohanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rohanButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(rohan.getSalary(false) + " LKR");
    }//GEN-LAST:event_rohanButtonActionPerformed

    private void keethButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keethButtonActionPerformed
        // TODO add your handling code here:
        salaryLabel.setText(keeth.getSalary(false) + " LKR");
    }//GEN-LAST:event_keethButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AllionSalaryCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AllionSalaryCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AllionSalaryCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AllionSalaryCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }

        try {
//            UIManager.setLookAndFeel(new FlatLightLaf());
            IntelliJTheme.setup(AllionSalaryCalculator.class.getResourceAsStream(
                    "/resources/themes/arc-theme.theme.json"));
            UIManager.put("Table.showHorizontalLines", true);
            UIManager.put("Table.showVerticalLines", true);
            UIManager.put("ScrollBar.showButtons", true);
            UIManager.put("ScrollBar.width", 16);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllionSalaryCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allEmployeesButton;
    private javax.swing.JButton andrewButton;
    private javax.swing.JButton brayanButton;
    private javax.swing.JButton donaldAndTeamButton;
    private javax.swing.JButton donaldButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kathrinaAndTeamButton;
    private javax.swing.JButton kathrinaButton;
    private javax.swing.JButton keethButton;
    private javax.swing.JButton nevilButton;
    private javax.swing.JButton rayanAndTeamButton;
    private javax.swing.JButton rayanButton;
    private javax.swing.JButton rohanButton;
    private javax.swing.JLabel salaryLabel;
    // End of variables declaration//GEN-END:variables
}
